main:
	pdflatex main.tex
full:
	pdflatex main.tex
	bibtex main
	pdflatex main.tex
	pdflatex main.tex
supp:
	pdflatex supplementary.tex
	bibtex supplementary
	pdflatex supplementary.tex
	pdflatex supplementary.tex
clean:
	rm -f main.aux main.blg main.fls main.brf main.fdb_latexmk main.fls main.log main.pdf main.out main.synctex.gz supplementary.aux supplementary.blg supplementary.fls supplementary.brf supplementary.fdb_latexmk supplementary.fls supplementary.log supplementary.pdf supplementary.out supplementary.synctex.gz rebuttal.aux rebuttal.bbl rebuttal.blg rebuttal.brf rebuttal.fdb_latexmk rebuttal.fls rebuttal.log rebuttal.out rebuttal.pdf rebuttal.synctex.gz
