#!/usr/bin/env python
import re
import sys

chunks = [[]]
for line in open(sys.argv[1]):
    if re.match(r'^\s*#', line) or re.match(r'^s*$', line):
        if not chunks or chunks[-1]:
            chunks.append([])
        continue
    chunks[-1].append(line)

for chunk in chunks:
    for line in chunk:
        if not line.startswith(' ') and not line.startswith('except'):
            print('>>>', line, end='')
        else:
            print('...', line, end='')
    exec(''.join(chunk))
