#! /bin/bash

# JBY: Autocrop.

if [ "$1" = "" ]; then
    echo "Automatically crops (a) images using convert -trim or (b) pdfs using pdfcrop."
    echo "Input filenames like filename.ext are converted to filename_crop.ext"
    echo "Files ending in _crop are skipped. Those that have already been converted to _crop"
    echo "versions are skipped based on timestamps, so it's safe to run, e.g.,"
    echo "  autocrop *pdf"
    echo "multiple times"
    echo
    echo "Usage:"
    echo " $0 file1 [ file 2 [ file 3 ... ] ]"
    exit 1
fi

while [ "$1" != "" ]; do
    filepath="$1"
    shift

    filedir=$(dirname "$filepath")
    filename=$(basename "$filepath")
    filebase="${filename%.*}"
    fileext="${filename##*.}"

    # Remove leading ./
    filedir="${filedir}/"
    if [ "$filedir" = "./" ]; then filedir=""; fi

    oldpath="${filedir}$filebase.$fileext"
    newpath="${filedir}${filebase}_crop.$fileext"

    if echo "$newpath" | grep "_crop_crop" >/dev/null; then
        echo "Skipping already cropped file $oldpath"
        continue
    fi

    if [ ! "$newpath" -nt "$oldpath" ]; then
        if [ "$fileext" = "pdf" ]; then
            pdfcrop "$oldpath" "$newpath" \
                && echo "$oldpath -> $newpath"
        else
            convert -trim +repage "$oldpath" "$newpath" \
                && echo "$oldpath -> $newpath"
        fi
    else
        echo "$oldpath -> $newpath (skipped; file already up to date)"
    fi
done
