name: Store Sync

on:
  issues:
    types: [reopened]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  SNAPSHOT_PATH: data/papers/gh-store-snapshot.json

concurrency:
  group: store-sync-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'stored-object')
    permissions:
      issues: write
      contents: write
    outputs:
      sync_id: ${{ steps.set-id.outputs.sync_id }}
    steps:
      - id: set-id
        run: echo "sync_id=${{ github.run_id }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: pip install gh-store
          
      - name: Sync Store
        run: |
          python -m gh_store process-updates \
            --issue ${{ github.event.issue.number }} \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --repo ${{ github.repository }}
            
          mkdir -p $(dirname ${{ env.SNAPSHOT_PATH }})
          python -m gh_store update-snapshot \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --repo ${{ github.repository }} \
            --snapshot-path ${{ env.SNAPSHOT_PATH }}
            
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update store snapshot [${{ github.run_id }}]"
          file_pattern: "${{ env.SNAPSHOT_PATH }}"

  notify-deploy:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      # This step apparently needs to be a manual API request like this because 
      # of security stuff around how workflows are allowed to trigger other workflows
      # or something to do with the token or some such, I don't really get it.
      - name: Trigger frontend deploy
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/2_deploy-frontend.yml/dispatches \
            -d "{\"ref\":\"${{ github.ref }}\",\"inputs\":{\"sync_id\":\"${{ needs.sync.outputs.sync_id }}\"}}"
