# .github/workflows/2_deploy-frontend.yml

name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      sync_id:
        required: true
        type: string
  push:
    paths:
      - 'data/store-snapshot.json'

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  wait-syncs:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Wait for syncs
        uses: actions/github-script@v7
        with:
          script: |
            const syncId = '${{ inputs.sync_id }}';
            while (true) {
              const runs = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.name,
                workflow_id: 'store-sync.yml',
                status: 'in_progress',
              });
              
              const earlierSyncs = runs.data.workflow_runs.filter(run => 
                run.id < parseInt(syncId)
              );
              
              if (earlierSyncs.length === 0) break;
              await new Promise(r => setTimeout(r, 10000));
            }

  deploy:
    needs: [wait-syncs]
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build site
        run: |
          mkdir -p _site
          cp -r frontend/* _site/
          cp data/store-snapshot.json _site/data/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
