# .github/workflows/build-extension.yml
name: Build Extension

on:
  push:
    paths:
      - 'extension/**'
      - '.github/workflows/build-extension.yml'
    branches: [ main, ext-use-gh-store ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension

    steps:
    - uses: actions/checkout@v4
    
    # Generate package-lock.json if it doesn't exist
    - name: Initialize npm
      run: |
        if [ ! -f "package-lock.json" ]; then
          npm install --package-lock-only --no-audit
        else
          echo "package-lock.json exists"
        fi
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './extension/package-lock.json'
        
    - name: Install dependencies
      run: npm ci --prefer-offline
        
    - name: Build extension
      run: npm run build

    # Debug output to see where files are
    - name: List files
      run: |
        pwd
        ls -lha .

    # Commit the built files
    - name: Commit bundled files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update extension bundles"
        file_pattern: "extension/*.bundle.js"
        # branch: bundled-extension
