name: Mirror Repository Issues

# This workflow requires a fine-grained PAT with access to both source and target repositories
# stored as a repository secret named DEV_REPO_TOKEN

on:
  workflow_dispatch:


jobs:
  mirror-repo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub fire loguru
    
    - name: Mirror repository issues
      run: |
        # Run the mirror script
        python github_repo_mirror.py --token $DEV_REPO_TOKEN
      env:
        DEV_REPO_TOKEN: ${{ secrets.DEV_REPO_TOKEN }} # Fine-grained PAT with access to both repos
