name: Process PDF with Grobid

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file relative to repository root'
        required: true
        type: string
      output_format:
        description: 'Output format (markdown/tei)'
        required: true
        type: choice
        options:
          - markdown
          - tei
        default: 'markdown'

jobs:
  convert:
    runs-on: ubuntu-latest
    services:
      grobid:
        image: lfoppiano/grobid:latest-crf
        ports:
          - 8070:8070
        options: >-
          --health-cmd "curl -sf http://localhost:8070/api/isalive || exit 1"
          --health-interval 30s
          --health-timeout 15s
          --health-retries 5
          --health-start-period 120s
          --memory 4g
          --memory-reservation 2g

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests loguru fire lxml

      - name: Wait for Grobid
        timeout-minutes: 5
        run: |
          echo "Waiting for Grobid to start..."
          while ! curl -sf http://localhost:8070/api/isalive > /dev/null; do
            sleep 10
            echo "Still waiting for Grobid... ($(date))"
          done
          echo "Grobid is ready"

      - name: Process PDF
        run: python .github/scripts/process_pdf.py ${{ github.event.inputs.pdf_path }} --format ${{ github.event.inputs.output_format }}

      - name: Upload processed file
        uses: actions/upload-artifact@v4
        with:
          name: processed-document
          path: output.*
          if-no-files-found: error
