name: Process PDF with Grobid

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file relative to repository root'
        required: true
        type: string
      output_format:
        description: 'Output format (markdown/tei)'
        required: true
        type: choice
        options:
          - markdown
          - tei
        default: 'markdown'

jobs:
  convert:
    runs-on: ubuntu-latest
    services:
      grobid:
        image: lfoppiano/grobid:latest-crf
        ports:
          - 8070:8070
        env:
          JAVA_OPTS: "-Xmx4g"
        volumes:
          - ${{ github.workspace }}:/opt/grobid/input
        options: >-
          --init
          --health-cmd "nc -z localhost 8070"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 240s

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests loguru fire lxml

      - name: Verify Grobid Service
        timeout-minutes: 5
        run: |
          echo "Waiting for Grobid to be ready..."
          for i in {1..30}; do
            if curl -sSf http://localhost:8070/api/isalive > /dev/null; then
              echo "Grobid is ready!"
              curl -v http://localhost:8070/api/version
              exit 0
            fi
            echo "Attempt $i: Service not ready yet, waiting..."
            sleep 10
          done
          echo "Grobid failed to start. Displaying logs:"
          docker logs $(docker ps -q --filter ancestor=lfoppiano/grobid:latest-crf)
          exit 1

      - name: Process PDF
        run: python .github/scripts/process_pdf.py ${{ github.event.inputs.pdf_path }} --format ${{ github.event.inputs.output_format }}

      - name: Upload processed file
        uses: actions/upload-artifact@v4
        with:
          name: processed-document
          path: output.*
          if-no-files-found: error
