name: Process PDF with Grobid

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file relative to repository root'
        required: true
        type: string
      output_format:
        description: 'Output format (markdown/tei)'
        required: true
        type: choice
        options:
          - markdown
          - tei
        default: 'markdown'

jobs:
  convert:
    runs-on: ubuntu-latest
    services:
      grobid:
        image: lfoppiano/grobid:latest-crf
        ports:
          - 8070:8070
        env:
          JAVA_OPTS: "-Xmx4g"
        volumes:
          - ${{ github.workspace }}:/opt/grobid/input
        options: "--init"
        
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests loguru fire lxml
    
      - name: Process PDF
        env:
          GROBID_HOST: localhost  # Updated from "grobid" to "localhost"
        run: |
          # Test service using localhost since the job is running on a VM
          for i in {1..30}; do
            if curl -sSf http://localhost:8070/api/isalive > /dev/null; then
              echo "Grobid is ready!"
              curl -v http://localhost:8070/api/version
              python .github/scripts/process_pdf.py ${{ github.event.inputs.pdf_path }} --format ${{ github.event.inputs.output_format }}
              exit 0
            fi
            echo "Attempt $i: Service not ready yet, waiting..."
            sleep 10
          done
          echo "Grobid failed to start. Displaying logs:"
          docker logs $(docker ps -q --filter ancestor=lfoppiano/grobid:latest-crf)
          exit 1

      - name: Upload processed file
        uses: actions/upload-artifact@v4
        with:
          name: processed-document
          path: output.*
          if-no-files-found: error
