name: Process PDF with Grobid

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file relative to repository root'
        required: true
        type: string
      output_format:
        description: 'Output format (markdown/tei)'
        required: true
        type: choice
        options:
          - markdown
          - tei
        default: 'markdown'

jobs:
  convert:
    runs-on: ubuntu-latest
    services:
      grobid:
        image: lfoppiano/grobid:latest-crf
        ports:
          - 8070:8070
        options: >-
          --health-cmd "curl -f http://localhost:8070/api/isalive || exit 1"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 6
          --health-start-period 60s
          -e JAVA_OPTS="-Xmx4g"
          --memory 5g
          --memory-swap 5g

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests loguru fire lxml

      - name: Wait for Grobid
        run: |
          timeout=120
          while [ $timeout -gt 0 ]; do
            if curl -sf http://localhost:8070/api/isalive > /dev/null; then
              echo "Grobid is ready"
              exit 0
            fi
            timeout=$((timeout - 5))
            echo "Waiting for Grobid to start... ${timeout}s remaining"
            sleep 5
          done
          echo "Grobid failed to start within timeout"
          docker logs $(docker ps -q --filter ancestor=lfoppiano/grobid:0.7.3)
          exit 1

      - name: Process PDF
        run: python .github/scripts/process_pdf.py ${{ github.event.inputs.pdf_path }} --format ${{ github.event.inputs.output_format }}

      - name: Upload processed file
        uses: actions/upload-artifact@v4
        with:
          name: processed-document
          path: output.*
          if-no-files-found: error
