# This workflow is triggered when we first create the
# issue defining a new enrichment. Still TBD how we
# want to integrate feature processing in the docunent
# processing pipeline. Probably a separate cronjob or
# an additional step on the PDF -> markdown job
name: Process New Enrichment Feature

on:
  issues:
    types: [opened, reopened]
  #workflow_dispatch:  # Allow manual triggering

jobs:
  process-features:
    if: contains(github.event.issue.labels.*.name, 'feature-node')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install llamero PyGithub duckduckgo-search
        
    - name: Process feature requests
      run: python scripts/process_enrichments.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ## Changed my mind. We'll leave these issues open to 
    ## indicate that these are the currently "active" features
    ## whose processing has been requested for all documents.
    ## Closing the issue for a feature will be used to indicate
    ## that its construction is no longer needed on documents
    ## future forward.
    # - name: Close Issue
    #   run: gh issue close "${{ github.event.issue.number }}"
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
