# .github/workflows/test-extension.yml
name: Test Extension

on:
  workflow_dispatch: # Allow manual triggering
  pull_request:
    paths:
      - 'extension/**'
  push:
    paths:
      - 'extension/**'
      - '.github/workflows/test-extension.yml'
    #branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './extension/package-lock.json'
    
    - name: Regenerate package-lock.json if needed
      run: |
        if [ -f "package-lock.json" ]; then
          rm -f package-lock.json
        fi
        npm install --package-lock-only --no-audit
    
    - name: Install dependencies
      run: npm ci --prefer-offline
    
    - name: Compile TypeScript tests
      run: tsc tests/source_detection.test.ts tests/integration.test.ts --module ESNext --target ES2020 --moduleResolution node --esModuleInterop true
    
    - name: Run source detection tests
      run: node tests/source_detection.test.js
    
    - name: Run integration tests
      run: node tests/integration.test.js
  
  build-extension:
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: extension
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './extension/package-lock.json'
    
    - name: Install dependencies
      run: |
        if [ ! -f "package-lock.json" ]; then
          npm install --package-lock-only --no-audit
        fi
        npm ci --prefer-offline
    
    - name: Type check
      run: npm run type-check
    
    - name: Build extension
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-build
        path: extension/dist/
